// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu2Vba3qQMyF0fMIGLw8sWcRXDpjC74HQ',
    appId: '1:87895171512:web:77e8577ddc7988f5712f4d',
    messagingSenderId: '87895171512',
    projectId: 'tradermind-b8ab2',
    authDomain: 'tradermind-b8ab2.firebaseapp.com',
    storageBucket: 'tradermind-b8ab2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqWNW5L1_VuqtTwStrXy8yaj0XHsYuh4Y',
    appId: '1:87895171512:android:fadf039e232c4db3712f4d',
    messagingSenderId: '87895171512',
    projectId: 'tradermind-b8ab2',
    storageBucket: 'tradermind-b8ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHHCWLCJMPGk41eqHcrqysjFO-Gw-iyU',
    appId: '1:87895171512:ios:aa78c33b63c784b8712f4d',
    messagingSenderId: '87895171512',
    projectId: 'tradermind-b8ab2',
    storageBucket: 'tradermind-b8ab2.firebasestorage.app',
    iosBundleId: 'com.example.tradermind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHHCWLCJMPGk41eqHcrqysjFO-Gw-iyU',
    appId: '1:87895171512:ios:aa78c33b63c784b8712f4d',
    messagingSenderId: '87895171512',
    projectId: 'tradermind-b8ab2',
    storageBucket: 'tradermind-b8ab2.firebasestorage.app',
    iosBundleId: 'com.example.tradermind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu2Vba3qQMyF0fMIGLw8sWcRXDpjC74HQ',
    appId: '1:87895171512:web:471575bc497ecfbd712f4d',
    messagingSenderId: '87895171512',
    projectId: 'tradermind-b8ab2',
    authDomain: 'tradermind-b8ab2.firebaseapp.com',
    storageBucket: 'tradermind-b8ab2.firebasestorage.app',
  );

}